name: GEMM PR Pre-checkin

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  run_gemm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ./go.sh
      - run: ls

