name: GEMM PR Pre-checkin

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  run_gemm:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - run: ./go.sh

